name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Set up Python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use your desired Python version

      - name: Install dependencies ğŸ”§
        run: |
          pip install sphinx sphinx_rtd_theme # Add any other Sphinx extensions you use

      - name: Build Sphinx documentation ğŸ“š
        run: sphinx-build -b html source build

      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v4 # Use the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publish to the 'protviz' subdirectory
          publish_dir: build/html
          destination_dir: protviz
          # If you want to keep the history of gh-pages branch, set keep_history: true
          # keep_history: true
